name: "Audit"

on:
  schedule:
    - cron: 0 9 * * 1
  pull_request:
    paths:
      - '**/package.json'
      - '**/pnpm-lock.yaml'

jobs:
  node:
    uses: timada-org/.github/.github/workflows/node-audit.yml@v1.1.1
